<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_New</name>
   <tag></tag>
   <elementGuidId>1e8f8e40-3236-4a6b-90d5-fcaa94d674bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div[title=&quot;New&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='brandBand_1']/div/div/div/div/lst-object-home/div/lst-list-view-manager/lst-common-list-internal/lst-list-view-manager-header/div/div/div[3]/div/ul/li/a/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;New&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d445c803-c2c8-4bc0-a627-19475db5eabc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>adf78007-d1bb-4592-8f91-4c96b651de95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>988:0</value>
      <webElementGuid>5ab2be58-3afc-48c0-982d-cdf1bf01d882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New</value>
      <webElementGuid>4f82c57a-8c94-4495-84c2-5af9d8d9c3ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_1&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;windowViewMode-maximized oneContent active lafPageHost&quot;]/div[@class=&quot;oneConsoleObjectHome&quot;]/div[@class=&quot;lstObjectHomeWrapper&quot;]/lst-object-home[1]/div[@class=&quot;slds-card slds-card_boundary slds-is-absolute&quot;]/lst-list-view-manager[1]/lst-common-list-internal[1]/lst-list-view-manager-header[1]/div[@class=&quot;slds-page-header slds-page-header_joined slds-page-header_bleed slds-page-header--object-home slds-page-header_object-home slds-shrink-none test-headerRegion slds-is-relative&quot;]/div[@class=&quot;slds-grid&quot;]/div[@class=&quot;slds-align_absolute-center&quot;]/div[@class=&quot;actionsWrapper slds-col slds-no-flex slds-grid slds-align-top slds-p-bottom--xx-small&quot;]/ul[@class=&quot;branding-actions slds-button-group slds-m-left--xx-small oneActionsRibbon forceActionsContainer&quot;]/li[@class=&quot;slds-button slds-button--neutral slds-button_neutral&quot;]/a[@class=&quot;forceActionLink&quot;]/div[1]</value>
      <webElementGuid>cb4f538c-6860-4c6e-924f-93a43c21c927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_1']/div/div/div/div/lst-object-home/div/lst-list-view-manager/lst-common-list-internal/lst-list-view-manager-header/div/div/div[3]/div/ul/li/a/div</value>
      <webElementGuid>b7e2cdd6-fa21-4bbd-b966-28b60f215059</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To unpin, pin another list view.'])[1]/following::div[4]</value>
      <webElementGuid>dcc479b1-beb5-4141-91a0-5d7ec7c042d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This list is pinned.'])[1]/following::div[4]</value>
      <webElementGuid>883a4580-10a3-420e-b60d-29c1f2bf8e84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/preceding::div[1]</value>
      <webElementGuid>ebc9cb94-63ec-4ac8-b323-bda99351e84d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Campaign'])[1]/preceding::div[2]</value>
      <webElementGuid>1f62df7a-1fe2-4218-8f2a-aadadf593236</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New']/parent::*</value>
      <webElementGuid>d3c8b697-be6d-4370-8294-60e22ed09598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a/div</value>
      <webElementGuid>8dddcbd5-e664-41c2-b05f-aeadb588136a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'New' and (text() = 'New' or . = 'New')]</value>
      <webElementGuid>128c5fb3-16e1-45d4-9134-8885909fee46</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
