<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_--None--</name>
   <tag></tag>
   <elementGuidId>3b2c870b-71fe-4cd8-8e15-efb9b1532c4d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#combobox-button-959</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='combobox-button-959']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=combobox[name=&quot;Country Code&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a3012d0b-4744-4269-b221-9c6e91fc1f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-combobox__input slds-input_faux fix-slds-input_faux slds-combobox__input-value</value>
      <webElementGuid>09a6067d-dd5e-44fe-81e2-d8cb019cecdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>combobox-button-959</value>
      <webElementGuid>1b499af7-dc54-459b-bff0-7de9fafb9f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61fbf262-10bc-44ec-9449-358fcbe868c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87976d20-3c65-4d4c-abe5-82d1dd0ade53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>af2d609d-dfcf-4d53-9bfe-7b023b7f7d70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Country_Code__c</value>
      <webElementGuid>5a7fb061-ae79-4927-9f76-353c66f6309b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>combobox</value>
      <webElementGuid>5092785e-7e30-4695-85af-6e4ca59af33e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>--None--</value>
      <webElementGuid>6a94cbfd-2952-4c00-b851-9c19e0a53404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b67263d2-dc3f-49ef-bbae-471f68da2e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Country Code</value>
      <webElementGuid>f0e496b5-a996-4e3a-9984-2c50cad4c26c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>86716c80-8320-4a24-94f1-9e26ec76f7d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input-button</value>
      <webElementGuid>fc2be8ad-f3c9-4f4b-8b13-76e376a0a8ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-controls</name>
      <type>Main</type>
      <value>dropdown-element-959</value>
      <webElementGuid>8edaf2a7-7b9b-4716-8e32-5805ee9446ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>db1f5c1b-3f49-484b-9e40-843cd0582f25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-text-958</value>
      <webElementGuid>f8a47a88-d596-4151-9228-4ed553b8874d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-position-id</name>
      <type>Main</type>
      <value>lgcp-1000022</value>
      <webElementGuid>0cff9573-5bbf-4667-b652-8c24c59a4485</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-activedescendant</name>
      <type>Main</type>
      <value>combobox-button-959-0-959</value>
      <webElementGuid>772aa7f3-3ddf-46af-91fd-40380143788d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--</value>
      <webElementGuid>187427f0-e7f7-4172-9bd7-eed588e7a10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;combobox-button-959&quot;)</value>
      <webElementGuid>4d581e3b-66e3-4b42-8e43-50da338c1887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='combobox-button-959']</value>
      <webElementGuid>e8a4d70e-d669-48a3-91b3-27da9008c142</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1292:0_content']/div/div[2]/div/div/div/lightning-input-field/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/button</value>
      <webElementGuid>5a3b4035-af0a-4011-bfc1-a4c0dc4e7281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[1]</value>
      <webElementGuid>3b2cb7e0-6ec2-4a16-9553-509b730ca9bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[3]/preceding::button[1]</value>
      <webElementGuid>012254da-c396-43ac-8af6-f9e1f3b2b139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/lightning-input-field/lightning-picklist/lightning-combobox/div/div/lightning-base-combobox/div/div/div/button</value>
      <webElementGuid>fbdcb1a7-dac7-490e-bcdb-176336c26f78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'combobox-button-959' and @type = 'button' and @name = 'Country_Code__c' and (text() = '--None--' or . = '--None--')]</value>
      <webElementGuid>c0e84219-6b58-4c52-ac02-7fe02974176d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
