<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create</name>
   <tag></tag>
   <elementGuidId>8ab993b9-6b8f-4480-9f2a-e78450004920</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;Create&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='Create']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Create&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eec9b7ce-6bf9-4672-a1fd-357a27654c91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b3d41fd3-a632-4588-802b-39c3e37bfcdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>3279043b-048b-402b-900c-09182502e461</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-button slds-button_brand</value>
      <webElementGuid>8105775d-4b2c-4b79-b917-4b05edfc8760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1538:0</value>
      <webElementGuid>38a1277f-e34b-4544-8dd1-69adeb9161db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create</value>
      <webElementGuid>c248a0b5-8784-476b-beee-46efe9306bf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;brandBand_2&quot;)/div[@class=&quot;slds-template__container&quot;]/div[@class=&quot;center oneCenterStage lafSinglePaneWindowManager&quot;]/div[@class=&quot;windowViewMode-normal oneContent active lafPageHost&quot;]/div[@class=&quot;overridePresent inlinePanel oneRecordActionWrapper&quot;]/div[@class=&quot;actionBody&quot;]/article[@class=&quot;slds-card cLead_RecordCreateForm&quot;]/div[@class=&quot;slds-card__body&quot;]/div[1]/form[@class=&quot;slds-form&quot;]/div[@class=&quot;slds-align_absolute-center slds-m-top_small slds-m-bottom_xx-large&quot;]/button[@class=&quot;slds-button slds-button_brand&quot;]</value>
      <webElementGuid>14479952-4da3-4833-a89b-05817fba3f39</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='Create']</value>
      <webElementGuid>0d812ead-b10a-48e8-83ae-1f99ae39de1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='brandBand_2']/div/div/div[3]/div/div/article/div[2]/div/form/div[2]/button[2]</value>
      <webElementGuid>0c56937d-d774-4f71-8f49-604e09dd3d16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[2]/following::button[1]</value>
      <webElementGuid>7cdf7b4e-f5d3-4fc2-a071-3401877afe27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Comments'])[1]/following::button[2]</value>
      <webElementGuid>2ad9a254-c15a-4e42-bac2-d91447f084b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No record selected'])[1]/preceding::button[1]</value>
      <webElementGuid>d221e5bb-027e-4e42-a1a9-2821ead1bf04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Just so you know'])[1]/preceding::button[1]</value>
      <webElementGuid>0fe552e7-edbb-46c0-a372-54912b40f80e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Create']/parent::*</value>
      <webElementGuid>e50c860b-5999-4f09-9d7e-ed73218f3dcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>1549595c-82e2-4e48-818b-0c6ee020921b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'Create' and (text() = 'Create' or . = 'Create')]</value>
      <webElementGuid>33dfcaae-4d85-4330-a11b-9881d9e822d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
