<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__MobilePhone</name>
   <tag></tag>
   <elementGuidId>81caf336-d3a6-4959-8cba-68299f556e03</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-920</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-920']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Mobile&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f6cec32e-6b7b-4e79-a211-791498696ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>8db0f758-d7d8-41a1-8bae-f7c16cbb69fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f8a7675b-4629-4ba2-a81a-d6befc31d11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-920</value>
      <webElementGuid>3aeff102-3154-420d-8cee-40365f9dace5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>ad282aaf-8a4d-4765-873f-800798ea3a43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>MobilePhone</value>
      <webElementGuid>8f9cddc1-3653-4cde-8119-ef17a860f223</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8ed15c7c-c8d6-4560-9acf-4551f5eacf4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-920</value>
      <webElementGuid>eb231de4-e319-4e34-8199-2a10327fc961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-920&quot;)</value>
      <webElementGuid>4809be80-d7e8-4534-b28e-d3962f0e645c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-920']</value>
      <webElementGuid>aee6bc2c-1c5c-4bd6-9ba8-26eba1f1eee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1292:0_content']/div/div[2]/div/div[2]/lightning-input-field/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>9e2fd413-83a9-41ad-90d7-ad28a9e095d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/lightning-input-field/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>796d0926-d9b0-4d68-b2cc-3935b2fd39f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-920' and @name = 'MobilePhone' and @type = 'text']</value>
      <webElementGuid>36cca2bc-d046-4e88-8399-0c16a0e794da</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
