<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__Company</name>
   <tag></tag>
   <elementGuidId>098f86fc-4865-4196-801d-0cc8767a122f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#input-938</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='input-938']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Company&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>66c83a5e-f8cf-411a-b0b4-b108f2be0074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-input</value>
      <webElementGuid>3da2fbc3-8131-498e-a537-39bc4b401ce3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>part</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d618fe19-162b-4612-92ee-e487aad24a79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>input-938</value>
      <webElementGuid>a67b3dea-f6f0-41bc-a828-8e0463301d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>33e69608-f84f-4671-b56c-cc911322a378</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Company</value>
      <webElementGuid>e99352a5-fe76-4eb5-b91f-87f0aed08f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8a26718f-b55e-4250-8fe2-af9e2b02aee6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>help-message-938</value>
      <webElementGuid>60ba6ddd-cbc4-4e1a-94bf-35bc30fa7ed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;input-938&quot;)</value>
      <webElementGuid>6a2c779a-4aab-43ed-b480-50edc58a1233</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='input-938']</value>
      <webElementGuid>79d82403-baa6-453f-8bcb-84a7cf393f1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1387:0_content']/lightning-input-field/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>c11a1459-7342-4fb8-b46a-f45b6c4c2a99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li/section/div[2]/lightning-input-field/lightning-input/lightning-primitive-input-simple/div/div/input</value>
      <webElementGuid>290b22e8-3768-4e3e-ab7f-19d7c0686c93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'input-938' and @name = 'Company' and @type = 'text']</value>
      <webElementGuid>98528080-9589-4ebc-8e80-732409f1c442</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
