<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lightning-primitive-icon</name>
   <tag></tag>
   <elementGuidId>1d1d2c9a-f68f-418d-b5f4-ca48e25e9339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>lightning-dual-listbox.slds-form-element_horizontal.slds-form-element.slds-has-error > div > div.slds-form-element__control > div.slds-dueling-list > div.slds-dueling-list__column > lightning-button-icon > button.slds-button.slds-button_icon.slds-button_icon-container > lightning-primitive-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='1387:0_content']/lightning-input-field[11]/lightning-picklist/lightning-dual-listbox/div/div[2]/div/div[4]/lightning-button-icon/button/lightning-primitive-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*Organization Criteria&quot;i >> internal:role=button[name=&quot;Move to Chosen Move selection to Chosen&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>lightning-primitive-icon</value>
      <webElementGuid>9e3cf4c8-0f24-4424-ba97-a4885decec10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>exportparts</name>
      <type>Main</type>
      <value>icon</value>
      <webElementGuid>f1ccf6eb-a96b-4204-8b60-de79de71181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>variant</name>
      <type>Main</type>
      <value>bare</value>
      <webElementGuid>9774f3d2-5a76-491b-a1f4-a2b35e755f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1387:0_content&quot;)/lightning-input-field[@class=&quot;slds-form-element slds-form-element_horizontal&quot;]/lightning-picklist[1]/lightning-dual-listbox[@class=&quot;slds-form-element_horizontal slds-form-element slds-has-error&quot;]/div[1]/div[@class=&quot;slds-form-element__control&quot;]/div[@class=&quot;slds-dueling-list&quot;]/div[@class=&quot;slds-dueling-list__column&quot;]/lightning-button-icon[1]/button[@class=&quot;slds-button slds-button_icon slds-button_icon-container&quot;]/lightning-primitive-icon[1]</value>
      <webElementGuid>e37afbcd-2c68-4d7f-a174-073b1c87e276</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1387:0_content']/lightning-input-field[11]/lightning-picklist/lightning-dual-listbox/div/div[2]/div/div[4]/lightning-button-icon/button/lightning-primitive-icon</value>
      <webElementGuid>26a2f6df-df99-4b85-b6a5-d547cebc9b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Either an annual turnover not exceeding AED 200 million/ $55 million'])[1]/following::lightning-primitive-icon[1]</value>
      <webElementGuid>bc28f6e4-9ea3-426e-b128-1bce7ef8b8f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Less than 250 employees'])[1]/following::lightning-primitive-icon[1]</value>
      <webElementGuid>841c2083-a973-44e3-a466-4cda5a6fff16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to Chosen'])[2]/preceding::lightning-primitive-icon[1]</value>
      <webElementGuid>6fc4dfa3-1968-4a20-9221-7cc92cf271da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move selection to Chosen'])[2]/preceding::lightning-primitive-icon[1]</value>
      <webElementGuid>1dd6bd51-1b86-453f-af96-70865ea4cbac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//lightning-input-field[11]/lightning-picklist/lightning-dual-listbox/div/div[2]/div/div[4]/lightning-button-icon/button/lightning-primitive-icon</value>
      <webElementGuid>2b124273-6da5-4167-bb37-743275d8b58b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
