<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--None--RadioWebsiteOutdoorFacebookInstagramLinkedInGoogleNewspaperExhibitionReferral</name>
   <tag></tag>
   <elementGuidId>503511de-84bc-4fd6-8643-a27ff5ec296b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='1449:0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;*How did you hear about us&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b552783d-40b5-4e32-bd6a-d9cb8f2ea85c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>da7116aa-c9cc-4f3f-92e0-130ed1301c9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1449:0</value>
      <webElementGuid>9f2cd9ff-4687-4663-b520-caafe6ba413e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slds-select</value>
      <webElementGuid>3b3afb67-3428-4338-98bc-29711f34360f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-aura-rendered-by</name>
      <type>Main</type>
      <value>1489:0</value>
      <webElementGuid>d6e0ffb4-56d8-4af3-8f81-5fd8a792ef87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>select1</value>
      <webElementGuid>a831c04c-d655-4cc3-a77f-d5db01d81ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>--None--RadioWebsiteOutdoorFacebookInstagramLinkedInGoogleNewspaperExhibitionReferral</value>
      <webElementGuid>e31fba00-c472-4d9a-8d19-c90bca1d188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1449:0&quot;)</value>
      <webElementGuid>d26cb9d9-f61e-45a3-8863-bec88a46797d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='1449:0']</value>
      <webElementGuid>d3d33f2f-04fe-44fa-8cf0-6acbbe3248d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='1432:0_content']/div/div/div/div/div/div/select</value>
      <webElementGuid>3bd4e84c-b87b-41a6-87eb-01fb8e295a34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How did you hear about us'])[1]/following::select[1]</value>
      <webElementGuid>d8f25854-0b64-46a7-9a87-18fa49197da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[12]/following::select[1]</value>
      <webElementGuid>775a23eb-93c5-400e-b76b-6a770b10d930</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='How did you hear about us'])[2]/preceding::select[1]</value>
      <webElementGuid>a01da0d9-5110-4117-9ee8-f504960e7f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='--None--'])[19]/preceding::select[1]</value>
      <webElementGuid>e4990d52-d375-49eb-a65d-22b31761e86f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>fe20c9da-2cb8-469b-a641-f17d45ae72ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = '1449:0' and @name = 'select1' and (text() = '--None--RadioWebsiteOutdoorFacebookInstagramLinkedInGoogleNewspaperExhibitionReferral' or . = '--None--RadioWebsiteOutdoorFacebookInstagramLinkedInGoogleNewspaperExhibitionReferral')]</value>
      <webElementGuid>28484a67-f3bc-429f-b498-65dc89b8403f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
