<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Verification Code_save</name>
   <tag></tag>
   <elementGuidId>d2dd1c72-f591-4a0e-b5e2-6e0051f7babc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Verify&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ce01ec8-ae25-4007-a11d-ae58296b7cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>b1c7ab07-3d95-4282-990f-404feaa63aa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button primary wide mt8 mb16</value>
      <webElementGuid>de66cf44-607a-475b-be5d-84a2a23707d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>c625c787-483b-4fe0-bdcf-628d14f5f42f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>save</value>
      <webElementGuid>4a8f1aee-47ba-4b21-893d-dc8845e71cc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Verify</value>
      <webElementGuid>4015a8c9-242c-4835-ae96-e7f92671ab80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>88f990f2-8e5d-46f0-9041-9a3be0d4a232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;save&quot;)</value>
      <webElementGuid>035d75e4-60bb-4e1d-87d2-eda0670c69c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='save']</value>
      <webElementGuid>775cf6c9-2a93-4cb7-b8af-6014367c3dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='editPage']/input[10]</value>
      <webElementGuid>203a4dc9-aced-4645-835a-b95731a8fe3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[10]</value>
      <webElementGuid>dbe19b2f-ca60-4f3a-b845-9bd0cce6bda2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'save' and @name = 'save' and @title = 'Verify' and @type = 'submit']</value>
      <webElementGuid>a9f146ae-caee-4612-a257-2bbb8ff7b4f2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
